services:
  api1:
    image: ararx-backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  api2:
    image: ararx-backend
    ports:
      - "8001:8000"
    env_file:
      - .env

  api3:
    image: ararx-backend
    ports:
      - "8002:8000"
    env_file:
      - .env

  loadbalancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
      - api3
