name: Test API with FastAPI and Postman

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "ALGORITHM=HS256" >> $GITHUB_ENV
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=1440" >> $GITHUB_ENV
          echo "APP_HOST=http://127.0.0.1:8000/" >> $GITHUB_ENV

      - name: Start FastAPI server
        run: |
          source venv/bin/activate
          python -m uvicorn api.api:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests with environment
        run: newman run tests/Routes.postman_collection.json -e tests/local.postman_environment.json
